### ISSUE TITLE
MultiCurl occasional crash in libcurl with https

### ISSUE THREAD

**Issue by andrii-suse** [openSUSE/libzypp#312] opened 2021-05-03 10:38 UTC
zypper occasionally crashes in MediaMultiCurl::multifetch when using https (libzypp libzypp-17.25.9-1.2):
```
Retrieving: patterns-base-minimal_base-20200505-14.1.x86_64.rpm ----------------------------------------------------------------[starting]
Segmentation fault (core dumped)
```
zypper.log has
```
2021-05-03 09:13:56 <5> 3335a2be6690(28) [zypp] ZYppFactory.cc(sigsegvHandler):54 [bt]: (15) /usr/lib64/libcurl.so.4 : +0x48545 [0x7fe82804c545]
2021-05-03 09:13:56 <5> 3335a2be6690(28) [zypp] ZYppFactory.cc(sigsegvHandler):54 [bt]: (16) /usr/lib64/libcurl.so.4 : curl_multi_perform+0xc6 [0x7fe82804cdb6]
2021-05-03 09:13:56 <5> 3335a2be6690(28) [zypp] ZYppFactory.cc(sigsegvHandler):54 [bt]: (17) /usr/lib64/libzypp.so.1722 : zypp::media::multifetchrequest::run(std::vector<zypp::Url, std::allocator<zypp::Url> >&)+0x1ea [0x7fe82891d40a]
2021-05-03 09:13:56 <5> 3335a2be6690(28) [zypp] ZYppFactory.cc(sigsegvHandler):54 [bt]: (18) /usr/lib64/libzypp.so.1722 : zypp::media::MediaMultiCurl::multifetch(zypp::filesystem::Pathname const&, _IO_FILE*, std::vector<zypp::Url, std::allocator<zypp::Url> >*, zypp::callback::SendReport<zypp::media::DownloadProgressReport>*, zypp::media::MediaBlockList*, long) const+0x42d [0x7fe82891f30d]
```
Full log: 
https://gist.githubusercontent.com/andrii-suse/b8ddf8976068b8926ba03926d0e98c67/raw/a99b73134d835bebbdb83248d71a201365b785d8/zypper.log

How to repeat on Tumbleweed:
```
sed -i 's,http://download.opensuse.org,https://mirrorcache.opensuse.org,g' /etc/zypp/repos.d/*repo
zypper install -y -t pattern kde kde_plasma
```

How to repeat with Dockerfile:
```
from registry.opensuse.org/opensuse/tumbleweed
RUN sed -i 's,http://download.opensuse.org,https://mirrorcache.opensuse.org,g' /etc/zypp/repos.d/*repo
RUN zypper --gpg-auto-import-keys ref
RUN zypper install -y -t pattern kde kde_plasma
```

Q: Why it crashes only with MirrorCache in *.repo file and doesn't crash with download.opensuse.org? 
A: download.opensuse.org reports mostly mirrors with http:// scheme, so MultiCurl uses http:// even if .repo files have https://download.opensuse.org - this is why no crash is observed.

**Comment by mlandres** [comment] 2021-05-03 11:12
Looks more like an issue between libcurl and mirrorcache.opensuse.org. In libyzpp it makes no difference, which URL you use.

**Comment by andrii-suse** [comment] 2021-05-03 11:23
MirrorCache only reports .metalink - file, e.g. https://mirrorcache-eu.opensuse.org/download/tumbleweed/repo/oss/x86_64/patterns-base-minimal_base-20200505-14.1.x86_64.rpm.metalink you see from the logs that MultiCurl doesn't use mirrorcache at the moment of crash - it uses mirrors the same way as with downloadd.opensuse.org . the only difference is https:// in mirrors

**Comment by mlandres** [comment] 2021-05-03 11:41
Yes, I see, but can not yet reproduce it. 
```
[zypp] MediaCurl.cc(doGetFileCopyFile):1139 URL: https://mirrorcache.opensuse.org/tumbleweed/repo/oss/x86_64/zypper-1.14.43-1.2.x86_64.rpm
[zypp] MediaCurl.cc(MediaCurl):192 MediaCurl::MediaCurl(https://mirror1.hs-esslingen.de/pub/Mirrors/ftp.opensuse.org/tumbleweed/repo/oss/x86_64/zypper-1.14.43-1.2.x86_64.rpm, )
[zypp] MediaCurl.cc(MediaCurl):192 MediaCurl::MediaCurl(https://ftp.tu-chemnitz.de/pub/linux/opensuse/tumbleweed/repo/oss/x86_64/zypper-1.14.43-1.2.x86_64.rpm, )
[zypp] MediaCurl.cc(MediaCurl):192 MediaCurl::MediaCurl(https://opensuse.schlundtech.de//tumbleweed/repo/oss/x86_64/zypper-1.14.43-1.2.x86_64.rpm, )
[zypp] MediaCurl.cc(MediaCurl):192 MediaCurl::MediaCurl(https://mirror.de.leaseweb.net/opensuse/tumbleweed/repo/oss/x86_64/zypper-1.14.43-1.2.x86_64.rpm, )
[zypp] MediaCurl.cc(MediaCurl):192 MediaCurl::MediaCurl(https://ftp.gwdg.de/pub/opensuse/tumbleweed/repo/oss/x86_64/zypper-1.14.43-1.2.x86_64.rpm, )
```
I just downloaded a bunch of packages, but had no issues.  Which exact versions do you have installed:
`zypper se -si '/^lib(openssl|curl|zypp)/'`

**Comment by andrii-suse** [comment] 2021-05-03 11:46
```
S | Name          | Type    | Version     | Arch   | Repository
--+---------------+---------+-------------+--------+------------------------
i | libcurl4      | package | 7.76.1-1.1  | x86_64 | openSUSE-Tumbleweed-Oss
i | libopenssl1_1 | package | 1.1.1k-2.1  | x86_64 | openSUSE-Tumbleweed-Oss
i | libzypp       | package | 17.25.9-1.2 | x86_64 | openSUSE-Tumbleweed-Oss
```

**Comment by andrii-suse** [comment] 2021-05-03 11:48
Hm, for me the problem easily reproducible in docker after installing ~100 packages, in my machine it did happen with 17.25.8 when I was updating ~100 packages as well, sometimes more often, sometimes less.

**Comment by mlandres** [comment] 2021-05-03 11:49
According to you backtrace it looks like it's inside a callback from libssl back into libcurl. But they are the same version an on my system.

**Comment by andrii-suse** [comment] 2021-05-03 12:03
Yeah I believe this one will be tricky. For me even `zypper refresh` crashes with clean cache: https://gist.github.com/andrii-suse/875cb58fb52563cb5dfef77137de8e08 . I will try to get more info then if you are sure there is nothing https-specific shared between threads inside libzypp.

**Comment by mlandres** [comment] 2021-05-03 12:09
You are sure the hardware is ok? Do you have come special openssl configuration?

Libzypp is exactly the same code as on Leap15* and SLE15*. We have by now no https issues there. 
Mabe we should file a bugreport for libcur/libopenssl. If TW has debuginfo packages, they may help to get a better backtrace.

**Comment by andrii-suse** [comment] 2021-05-03 12:27
I can easily reproduce in CircleCI cloud, so hardware is not an issue https://gist.github.com/andrii-suse/e77018ce5671e3b037a54677c47a4af4 .
zypper never used MultiCurl with https because download.opensuse.org always was reporting mirrors with http:// . And I don't see a problem when setting `download.max_concurrent_connections = 0` in zypp.conf , so I don't think it is some straightforward issue which somebody could observe before.
But if you are unable to reproduce it - I will try to get more info

**Comment by mlandres** [comment] 2021-05-03 13:03
We should take this to bugzilla and ask the curl/openssl maintainers how to hunt this. All crashes are depp inside libcurl below curl_multi_perform, even below libssl.

**Comment by mlandres** [comment] 2021-05-03 13:39
JFYI: I switched my systems to use https://mirrorcache.opensuse.org. Maybe i can catch it somewhere. By now my 15.2 has successfully downloaded 1296 packages via https and multicurl. Libzypp version is 17.25.10 on all systems.

**Comment by mlandres** [comment] 2021-05-03 14:04
@andrii-suse I'd open an bug for curl/ssl if you did not do it yet.
```           PID: 14756 (zypper)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Mon 2021-05-03 13:49:49 UTC (1min 59s ago)
  Command Line: zypper up --download-only
    Executable: /usr/bin/zypper
 Control Group: /user.slice/user-0.slice/session-48.scope
          Unit: session-48.scope
         Slice: user-0.slice
       Session: 48
     Owner UID: 0 (root)
       Boot ID: 3a9cb7d6a1ba4d4ab2d0b669a7695896
    Machine ID: 03e243a12ac7eaea1fbb4143b23406bd
      Hostname: zypp-head
       Storage: /var/lib/systemd/coredump/core.zypper.0.3a9cb7d6a1ba4d4ab2d0b669a7695896.14756.1620049789000000.lz4
       Message: Process 14756 (zypper) of user 0 dumped core.
                
                Stack trace of thread 14756:
                #0  0x00007fe484a3aad0 Curl_ssl_getsessionid.constprop.0 (libcurl.so.4 + 0x6fad0)
                #1  0x00007fe484a2e9b2 ossl_new_session_cb (libcurl.so.4 + 0x639b2)
                #2  0x00007fe48403c2fd ssl_update_cache (libssl.so.1.1 + 0x3d2fd)
                #3  0x00007fe48405a1d7 ossl_statem_client_process_message (libssl.so.1.1 + 0x5b1d7)
                #4  0x00007fe48404cb45 read_state_machine (libssl.so.1.1 + 0x4db45)
                #5  0x00007fe484050ce8 state_machine (libssl.so.1.1 + 0x51ce8)
                #6  0x00007fe484026308 ssl3_read_bytes (libssl.so.1.1 + 0x27308)
                #7  0x00007fe484032413 ssl3_read_internal (libssl.so.1.1 + 0x33413)
                #8  0x00007fe4840367e3 SSL_read (libssl.so.1.1 + 0x377e3)
                #9  0x00007fe484a39d53 ossl_recv (libcurl.so.4 + 0x6ed53)
                #10 0x00007fe4849f63dc http2_conncheck.lto_priv.0 (libcurl.so.4 + 0x2b3dc)
                #11 0x00007fe484a2fe9f extract_if_dead.part.0.lto_priv.0 (libcurl.so.4 + 0x64e9f)
                #12 0x00007fe484a25275 ConnectionExists.lto_priv.0 (libcurl.so.4 + 0x5a275)
                #13 0x00007fe484a13839 multi_runsingle (libcurl.so.4 + 0x48839)
                #14 0x00007fe484a13db6 curl_multi_perform (libcurl.so.4 + 0x48db6)
                #15 0x00007fe4852d3f83 _ZN4zypp5media17multifetchrequest3runERSt6vectorINS_3UrlESaIS3_EE (libzypp.so.1722 + 0x1e6f83)
```

**Comment by andrii-suse** [comment] 2021-05-03 14:37
I am not sure if libzypp or zypper satisfy these requirements `OpenSSL can safely be used in multi-threaded applications provided that at least two callback functions are set` from https://linux.die.net/man/3/crypto_set_id_callback taken from here https://curl.se/libcurl/c/threadsafe.html

**Comment by mlandres** [comment] 2021-05-03 14:45
We do not use threads in libyzpp.

**Comment by mlandres** [comment] 2021-05-03 14:46
Moving to bugzills: [bsc#1185579](https://bugzilla.suse.com/show_bug.cgi?id=1185579)

**Closed** 2021-05-03 14:52 UTC
